x-logging: &default-logging
  driver: json-file
  options:
    max-size: 10m
    max-file: 3

services:
  frontend:
    build:
      context: frontend
    env_file:
      - frontend/.env
    volumes:
      - frontend:/app/frontend/dist

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - db:/data/db
    ports:
      - 127.0.0.1:27018:27017
    networks:
      - internal
    logging: *default-logging

  backend:
    restart: always
    build:
      context: backend
    env_file:
      - backend/.env
    volumes:
      - ./backend/src:/app/src
      - public:/app/src/public
    ports:
      - 127.0.0.1:3000:3000
    networks:
      - internal
    depends_on:
      - mongo
    logging: *default-logging

  server:
    build:
      context: nginx
    ports:
      - 80:80
    volumes:
      - frontend:/var/app
      - public:/var/public
    depends_on:
      - frontend
      - backend
    networks:
      - internal
    logging: *default-logging

volumes:
  frontend:
  public:
  db:

networks:
  internal:
