name: Project tests

on:
  pull_request:
  push:
    branches:
      - main
      - review

env:
  COMPOSE_PROJECT_NAME: bad-server
  DIR_PROJECT: ${{ github.workspace }}

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      DIR_TESTS: /tmp/tests-bad-server
      REP_TESTS: https://github.com/Yandex-Practicum/tests-bad-server.git
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Download project tests
        run: git clone --depth 1 "$REP_TESTS" "$DIR_TESTS"
      - name: Start project
        run: bash "$DIR_TESTS/bin/start_project.sh"
      - name: Run tests
        run: bash "$DIR_TESTS/bin/run.sh"
